### ISSUE TITLE
Report on Godot 4.0 breaking changes that impact Popochiu 1.x

### ISSUE THREAD

**Issue by stickgrinder** [mapedorr/popochiu#12]
We need a precise list of changes for Popochiu to work on Godot 4.0.

To achieve this we may want to:

* [ ] Check for available Godot 3 to 4 migration paths online (some links below) and list all the impacted area in a comment
  * https://www.reddit.com/r/godot/comments/tsxgnj/migrating_from_3x_to_40/ 
  * https://gist.github.com/WolfgangSenff/168cb0cbd486c8c9cd507f232165b976
  * https://www.youtube.com/watch?v=ZjfYZPjLdQU
* [ ] Take note about all deprecation notices currently raised by Godot 3.6 in Popochiu 1.x (ex. Navigation2D is deprecated for NavigationServer - there may be more) 
* [ ] Open `popochiu-dev` project in Godot 4.0 and take note / solve all the smallest issues (this will surely help but may become a bit of a "one at a time" sort of endeavor)

Should this issue be solvable in a single pass, it's easier to just commit the upgrades on it. If more work is required is better to open new issues under the same milestone.

**Comment by mapedorr** [comment]
Maybe we should start by fixing the addon first, instead of trying to fix things in `popochiu-dev`. In the end, the game is created using the plugin classes and scripts, so fixing the plugin should allow us to create the development game from it.

**Comment by stickgrinder** [comment]
@mapedorr not sure what's the difference in working on the dev repo. Nothing against this, just asking,

**Comment by mapedorr** [comment]
That there will be less things to fix as we will not have to fix bugs that are part of the demo itself @stickgrinder . But maybe I'm wrong, as importing the dev project directly in Godot 4 will run the script the Godot team created to migrate projects from 3.x to 4.x.

**Comment by mapedorr** [comment]
# Things to test before the first beta release

Now that most of the plugin is working, there are some things we need to test in order to fix bugs and make sure all v1.x functionalities are ready.

## Editor

- [ ] Installation: At the moment of writing, the installation is working, but one needs to restart the engine after pasting **popochiu** inside the **addons** folder in order for it to work when the plugin is enabled in *Project settings / Plugins*.
- [ ] Create room.
- [ ] Create prop.
- [ ] Create hotspot.
- [ ] Create walkable area.
- [ ] Create region.
- [ ] Create character.
- [ ] Create inventory item.
- [ ] Create dialog.
- [ ] Make sure the plugin does something if it is marked as Pixel, or 2D: This is something we have to control at node level now that Godot 4 moved that from the import flags to the `CanvasItem.texture_filter` property.

## Engine

- [ ] Save/Load (now Window):
  - [ ] Save working
  - [ ] Load working
  - [ ] The popup font looks blurry
  - [ ] The cursor dissapears when it enters the window
  - [ ] Closing the popup does not make it dissapear completely, looks like its panel container keeps visible, and that blocks interactions.

- [ ] Show in-line dialog.
- [ ] Remove inventory items.
- [ ] Play custom character animations.
- [ ] Change playable character.

**Comment by stickgrinder** [comment]
> That there will be less things to fix as we will not have to fix bugs that are part of the demo itself @stickgrinder . But maybe I'm wrong, as importing the dev project directly in Godot 4 will run the script the Godot team created to migrate projects from 3.x to 4.x.

Ah I see! Well, I guess you are right.
The absence of a dependency manager for Godot is making this more painful that it needs to be :P But I guess you're right!

Sorry for taking so long to reply. I guess we can coordinate to address the list items in the next days, so we can speed the process up maybe?

**Comment by mapedorr** [comment]
I'm gonna close this issue because of the release of [v2.0-alpha1](https://github.com/mapedorr/popochiu/tree/v2.0-alpha1). I'll create another issue just to keep track of the pending things.
